apr/config/routes.rb
Rails.application.routes.draw do
  resources :criterion_files
  resources :criterion_sub_details
  resources :criterion_details
  resources :criterions
  resources :units
  resources :users
  resources :action_plans

  root 'home#instructions'

  get 'home/instructions'

  get 'logout' => 'application#logout'

end

apr/app/models/criterion.rb
class Criterion < ActiveRecord::Base
end

apr/app/controllers/criterions_controller.rb
class CriterionsController < ApplicationController
  before_action :set_criterion, only: [:show, :edit, :update, :destroy]

  # GET /criterions
  # GET /criterions.json
  def index
    @criterions = Criterion.all
  end

  # GET /criterions/1
  # GET /criterions/1.json
  def show
  end

  # GET /criterions/new
  def new
    @criterion = Criterion.new
  end

  # GET /criterions/1/edit
  def edit
  end

  # POST /criterions
  # POST /criterions.json
  def create
    @criterion = Criterion.new(criterion_params)

    respond_to do |format|
      if @criterion.save
        format.html { redirect_to @criterion, notice: 'Criterion was successfully created.' }
        format.json { render :show, status: :created, location: @criterion }
      else
        format.html { render :new }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criterions/1
  # PATCH/PUT /criterions/1.json
  def update
    respond_to do |format|
      if @criterion.update(criterion_params)
        format.html { redirect_to @criterion, notice: 'Criterion was successfully updated.' }
        format.json { render :show, status: :ok, location: @criterion }
      else
        format.html { render :edit }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criterions/1
  # DELETE /criterions/1.json
  def destroy
    @criterion.destroy
    respond_to do |format|
      format.html { redirect_to criterions_url, notice: 'Criterion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criterion
      @criterion = Criterion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterion_params
      params.require(:criterion).permit(:criterion_number, :description)
    end
end

apr/app/helpers/criterions_helper.rb
module CriterionsHelper
end

apr/app/views/criterions/_form.html.erb
<%= form_for(@criterion) do |f| %>
  <% if @criterion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@criterion.errors.count, "error") %> prohibited this criterion from being saved:</h2>

      <ul>
      <% @criterion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :criterion_number %><br>
    <%= f.number_field :criterion_number %>
  </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :field1, "Field 1 Text" %><br>
      <%= f.text_field :field1 %>
    </div>
    <div class="field">
      <%= f.label :field2, "Field 2 Text" %><br>
      <%= f.text_field :field2 %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

apr/app/views/criterions/edit.html.erb
<h1>Editing Criterion</h1>

<%= render 'form' %>

<%= link_to 'Show', @criterion %> |
<%= link_to 'Back', criterions_path %>

apr/app/views/criterions/index.html.erb
<p id="notice"><%= notice %></p>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<div>
<h1>Listing Criterions</h1>

<table class= "table table-striped">
  <thead>
    <tr>
      <th><center>Criterion#</center></th>
      <th><center>Description</center></th>
      <th><center>Field 1 Text</center></th>
      <th><center>Field 2 Text</center></th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @criterions.each do |criterion| %>
      <tr>
        <td><center><%= criterion.criterion_number %></center></td>
        <td><%= criterion.description %></td>
        <td><%= criterion.field1 %></td>
        <td><%= criterion.field2 %></td>
        <td><center>
          <div class="btn-group">
            <%= link_to 'Show', criterion, class: "btn" %>
        <%= link_to 'Edit', edit_criterion_path(criterion), class: "btn", style: 'color: purple;' %>
  <%= link_to 'Destroy', criterion, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn", style: 'color: red;' %>
      </center></td></div>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<p class="link-position-right"><%= link_to 'Add New Criterion', new_criterion_path, class: "btn btn-primary"  %></p>

apr/app/views/criterions/new.html.erb
<h1>New Criterion</h1>

<%= render 'form' %>

<%= link_to 'Back', criterions_path %>

apr/app/views/criterions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Criterion number:</strong>
  <%= @criterion.criterion_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @criterion.description %>
</p>

<p>
  <strong>Field 1 Text:</strong>
  <%= @criterion.field1 %>
</p>

<p>
  <strong>Field 2 Text:</strong>
  <%= @criterion.field2 %>
</p>

<%= link_to 'Edit', edit_criterion_path(@criterion) %> |
<%= link_to 'Back', criterions_path %>