apr/config/routes.rb
Rails.application.routes.draw do
  resources :criterion_files
  resources :criterion_sub_details
  resources :criterion_details
  resources :criterions
  resources :units
  resources :users
  resources :action_plans

  root 'home#instructions'

  get 'home/instructions'

  get 'logout' => 'application#logout'

end

apr/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def instructions
  end
end

apr/app/helpers/home_helper.rb
module HomeHelper
end

apr/app/views/home/index.html.erb
<div id="sc" class="container">
  <div class="row">
    <div class="col-lg-3 col-md-9">
      <h1></h1>

      <!--<div class="navbar-collapse collapse slidebar-nav">
        <ul class="nav">
          <li><a class="active" href="#">Instructions</a></li>
          <li><a href="#">Title Page</a></li>
          <li><a href="#">Criterion 1</a></li>
          <li><a href="#">Criterion 2</a></li>
        </ul>
      </div>-->

      <div class="navbar-collapse collapse slidebar-nav">
        <% if !User.find_by_username(session[:cas_user].to_s).blank? %>
            <% if session[:cas_user].to_s.eql?(User.find_by_username(session[:cas_user].to_s).username) && User.find_by_username(session[:cas_user].to_s).role.to_s.eql?("Admin") then %>
                <ul class="nav">
                  <li><%= link_to("Home", home_instructions_path) %></li>
                  <li><%= link_to("APR Reports", action_plans_path) %></li>
                  <li><%= link_to("Criteria", criterions_path) %></li>
                  <li><%= link_to("Users", users_path) %></li>
                  <li><%= link_to("Units", units_path) %></li>
                </ul>
            <% else %>
                <ul class="nav">
                  <li><%= link_to("Home", home_instructions_path) %></li>

                  <%# --------- Action Plan -------------------%>
                  <% if ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s).id).blank? then %>
                      <li><%= link_to("Title page", new_action_plan_path) %></li>
                  <% else %>
                      <li><%= link_to("Title page", edit_action_plan_path(:id => ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s).id).id)) %></li>
                  <% end %>

                  <%# --------- Show Criterions only if Action Plan is created -------------------%>
                  <% if !ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s).id).blank? %>
                      <%# --------- Criterion 1 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(1).id).blank? then %>
                          <li><%= link_to("Criterion 1", new_criterion_detail_path(:cr => 1)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 1", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(1).id).id,
                                                                                    :cr => 1)) %></li>
                      <% end %>

                      <%# --------- Criterion 2 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(2).id).blank? then %>
                          <li><%= link_to("Criterion 2", new_criterion_detail_path(:cr => 2)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 2", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(2).id).id,
                                                                                    :cr => 2)) %></li>
                      <% end %>

                      <%# --------- Criterion 3 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(3).id).blank? then %>
                          <li><%= link_to("Criterion 3", new_criterion_detail_path(:cr => 3)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 3", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(3).id).id,
                                                                                    :cr => 3)) %></li>
                      <% end %>

                      <%# --------- Criterion 4 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(4).id).blank? then %>
                          <li><%= link_to("Criterion 4", new_criterion_detail_path(:cr => 4)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 4", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(4).id).id,
                                                                                    :cr => 4)) %></li>
                      <% end %>

                      <%# --------- Criterion 5 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(5).id).blank? then %>
                          <li><%= link_to("Criterion 5", new_criterion_detail_path(:cr => 5)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 5", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(5).id).id,
                                                                                    :cr => 5)) %></li>
                      <% end %>

                      <%# --------- Criterion 6 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(6).id).blank? then %>
                          <li><%= link_to("Criterion 6", new_criterion_detail_path(:cr => 6)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 6", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(6).id).id,
                                                                                    :cr => 6)) %></li>
                      <% end %>

                      <%# --------- Criterion 7 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(7).id).blank? then %>
                          <li><%= link_to("Criterion 7", new_criterion_detail_path(:cr => 7)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 7", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(7).id).id,
                                                                                    :cr => 7)) %></li>
                      <% end %>

                      <%# --------- Criterion 8 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(8).id).blank? then %>
                          <li><%= link_to("Criterion 8", new_criterion_detail_path(:cr => 8)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 8", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(8).id).id,
                                                                                    :cr => 8)) %></li>
                      <% end %>

                      <%# --------- Criterion 9 -------------------%>
                      <% if CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(9).id).blank? then %>
                          <li><%= link_to("Criterion 9", new_criterion_detail_path(:cr => 9)) %></li>
                      <% else %>
                          <li><%= link_to("Criterion 9", edit_criterion_detail_path(:id => CriterionDetail.find_by_action_plan_id_and_criterion_id(ActionPlan.find_by_user_id(User.find_by_username(session[:cas_user].to_s)).id, Criterion.find_by_criterion_number(9).id).id,
                                                                                    :cr => 9)) %></li>
                      <% end %>
                  <% end %>
                </ul>
            <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-lg-9 col-md-9">
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

apr/app/views/home/instructions.erb
<% if User.find_by_username(session[:cas_user].to_s).blank? %>
    <h1>Unauthorized Access</h1>

    <p>It seems you are not a user who is configured in our database. So, you are not authorized to access this site. Please contact <a href="mailto:vamshins@unm.edu?Subject=Access%20authorization" target="_top">vamshins@unm.edu</a> for further information.</p>

<% else %>
    <h1>Instructions</h1>


    <p>The unit should prepare an initial action plan based upon the entire APR process. The unit’s action plan should
      reflect both short-term and long-term action items that are aligned with the goals and mission of the unit,
      college/school, and university. The action items should be feasible with respect to the program/department/unit,
      college, and university resources; sustainable; and measurable. The action plan should address any shortcomings
      noted
      by the APR review team with respect to the APR Criterion, be reflective of any goals of the program based upon
      the
      unit’s mission and strategic planning initiatives, and take into account the review team’s recommendations or
      comments, where appropriate.
    </p>

    <p>The initial action plan or the annual update to the action plan should be arranged according to UNM’s current
      Academic Program Review Criteria (see attached document or refer to the APR Policy Manual found at apr.unm.edu).
      Comments or a brief narrative explaining the action items or updates should be included at the end of each
      Criterion
      section.
    </p>

    <p>Each action item should include:</p>

    <ol type="1">
      <li>A description of the action item and associated tasks written in measurable terms with appropriate
        measurable
        outcome(s)/metrics.
      </li>
      <li>The person(s) responsible for this action</li>
      <li>Resources needed for completing the action item (if there are budgetary requirements, please indicate the
        amount,
        funding source, and approvals for the funding source).
        <strong><i>If an action item requires significant external resources, a plan for how those resources will be
          obtained must be provided.</i></strong>
      </li>

      <li>A timeline for implementation with the projected start date and target date for completion.</li>

      <li>The current status of the item or task</li>
    </ol>

<% end %>