apr/config/routes.rb
Rails.application.routes.draw do
  resources :criterion_files
  resources :criterion_sub_details
  resources :criterion_details
  resources :criterions
  resources :units
  resources :users
  resources :action_plans

  root 'home#instructions'

  get 'home/instructions'

  get 'logout' => 'application#logout'

end

apr/app/models/action_plan.rb
class ActionPlan < ActiveRecord::Base
	belongs_to :unit

	validates :unit_id, presence: {message: "must be selected!"}
	validates :submitter_first_name, presence: {message: "cannot be blank!"}
	validates :submitter_last_name, presence: {message: "cannot be blank!"}
	validates :submitter_title, presence: {message: "cannot be blank!"}
	validates :user_id, presence: {message: "cannot be blank!"}
end

apr/app/models/criterion.rb
class Criterion < ActiveRecord::Base
end

apr/app/models/criterion_detail.rb
class CriterionDetail < ActiveRecord::Base
  belongs_to :action_plan
  belongs_to :criterion
end

apr/app/models/criterion_file.rb
class CriterionFile < ActiveRecord::Base
  belongs_to :criterion_detail
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the file name is present.
end

apr/app/models/criterion_sub_detail.rb
class CriterionSubDetail < ActiveRecord::Base
  belongs_to :criterion_detail
end

apr/app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :action_plans
end

apr/app/models/user.rb
class User < ActiveRecord::Base
end

apr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :cas_filter
 
  def cas_filter
    RubyCAS::Filter.filter(self)
  end

  def logout
  	reset_session
  	RubyCAS::Filter.logout(self)
  end
end

apr/app/controllers/criterions_controller.rb
class CriterionsController < ApplicationController
  before_action :set_criterion, only: [:show, :edit, :update, :destroy]

  # GET /criterions
  # GET /criterions.json
  def index
    @criterions = Criterion.all
  end

  # GET /criterions/1
  # GET /criterions/1.json
  def show
  end

  # GET /criterions/new
  def new
    @criterion = Criterion.new
  end

  # GET /criterions/1/edit
  def edit
  end

  # POST /criterions
  # POST /criterions.json
  def create
    @criterion = Criterion.new(criterion_params)

    respond_to do |format|
      if @criterion.save
        format.html { redirect_to @criterion, notice: 'Criterion was successfully created.' }
        format.json { render :show, status: :created, location: @criterion }
      else
        format.html { render :new }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criterions/1
  # PATCH/PUT /criterions/1.json
  def update
    respond_to do |format|
      if @criterion.update(criterion_params)
        format.html { redirect_to @criterion, notice: 'Criterion was successfully updated.' }
        format.json { render :show, status: :ok, location: @criterion }
      else
        format.html { render :edit }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criterions/1
  # DELETE /criterions/1.json
  def destroy
    @criterion.destroy
    respond_to do |format|
      format.html { redirect_to criterions_url, notice: 'Criterion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criterion
      @criterion = Criterion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterion_params
      params.require(:criterion).permit(:criterion_number, :description)
    end
end

apr/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def instructions
  end
end

apr/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:unit, :college)
    end
end

apr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :role)
    end
end

apr/app/helpers/action_plans_helper.rb
module ActionPlansHelper
end

apr/app/helpers/application_helper.rb
module ApplicationHelper
end

apr/app/helpers/criterion_details_helper.rb
module CriterionDetailsHelper
end

apr/app/helpers/criterion_files_helper.rb
module CriterionFilesHelper
end

apr/app/helpers/criterions_helper.rb
module CriterionsHelper
end

apr/app/helpers/home_helper.rb
module HomeHelper
end

apr/app/helpers/units_helper.rb
module UnitsHelper
end

apr/app/helpers/users_helper.rb
module UsersHelper
end

apr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apr</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'home', media: 'all' %> <!-- home.scss -->
  <%= csrf_meta_tags %>
</head>
<body>
<!--<div id="logged-in">-->
<!--Signed in as <SPAN id="top-username"> <%= session[:cas_user] %></SPAN>. Not you?-->
<!--<%= link_to("Sign Out", logout_path) %>-->
<!--</div>-->
<!--<div id="wrapper">-->
<!--<div id="head">-->
<!--<div id="banner">-->
<!--<img src="/assets/banner.jpg"/>-->

<div class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin: 0px;">

  <div class="container-fluid">
    <!-- Navigation bar Header -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-bar-apr-collapse">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">University of New Mexico</a>
    </div>

    <!--<div class="navbar-header navbar-right">-->
    <div class="collapse navbar-collapse navbar-right" id="nav-bar-apr-collapse">
            <ul class="nav navbar-nav">
              <li><a href="#">Signed in as <%= session[:cas_user] %>. Not you?</a></li>
              <li><%= link_to("Sign Out", logout_path) %></li>
            </ul>
    </div>
  </div>

</div>
<br><br>
<!-- Page Header -->
<div class="page-header no-margin no-padding">
  <div class="container">
    <img src="/assets/banner.jpg" class="img-responsive full-width">
  </div>
</div>

<div id="content">
  <%= render template:'home/index' %>
</div>
<br><br>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h4>Pysical Address</h4>
        Scholes Hall
        <br>
        Room 240
        <br>
        Phone: (505) 277-4130
        <br>
        Fax: (505) 277-8275
        <br>
        Email:
        <a href="mailto:apr@unm.edu">apr@unm.edu</a>
      </div>
      <div class="col-sm-4">
        <h4>Mailing Address</h4>
        Academic Program Review
        <br>
        MSC05 3400
        <br>
        1 University of New Mexico
        <br>
        Albuquerque, NM 87131-0001
      </div>
      <div class="col-sm-4">
        <p>
          <a href="http://unm.edu"></a>
          <img src="https://webcore.unm.edu/v2/images/unm-transparent-white.png" alt="The University of New Mexico">
        </p>
        <small>
          alt="The University of New Mexico"
          <br>
          Albuquerque, NM 87131, (505) 277-0111
          <br>
          New Mexico's Flagship University
        </small>
      </div>
    </div>
  </div>
</div>
</body>
</html>


<!--
 <div id="navbar" class="navbar-collapse collapse">
          <#% if session[:cas_user].to_s == User.find_by_username(session[:cas_user].to_s) && User.find_by_username(session[:cas_user].to_s).role.to_s == "Admin" then %>
              <ul class="nav navbar-nav">
                <li><a href="#">Home</a></li>
              </ul>
          <#% else %>
              <ul class="nav navbar-nav">
                <li><#%= link_to("Home", home_index_path) %></li>
                <li><#%= link_to("APR Reports", action_plans_path) %></li>
                <li><a href="/criterions/">Criteria</a></li>
                <li><a href="#">Signed in as<#%= session[:cas_user] %>. Not you?</a></li>
                <li><a href="#">Sign Out</a></li>
              </ul>
          <#% end %>

##Page Header
<div class="page-header no-margin no-padding">
  <div class="container">
    <img src="/assets/banner.jpg" class="img-responsive full-width">
  </div>
</div>

-->